//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GrapeCity.ActiveReports.Samples.EndUserDesigner.Properties {
    using System;
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrapeCity.ActiveReports.Samples.EndUserDesigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdNewReport {
            get {
                object obj = ResourceManager.GetObject("CmdNewReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdOpen {
            get {
                object obj = ResourceManager.GetObject("CmdOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdOpenFromServer {
            get {
                object obj = ResourceManager.GetObject("CmdOpenFromServer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdSave {
            get {
                object obj = ResourceManager.GetObject("CmdSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdSaveAs {
            get {
                object obj = ResourceManager.GetObject("CmdSaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CmdSaveToServer {
            get {
                object obj = ResourceManager.GetObject("CmdSaveToServer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports_CSV.csv.
        /// </summary>
        internal static string CsvFileName {
            get {
                return ResourceManager.GetString("CsvFileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to CSV Files (*.csv)|*.csv|All files (*.*)|*.*.
        /// </summary>
        internal static string CsvFilter {
            get {
                return ResourceManager.GetString("CsvFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Untitled.rdlx.
        /// </summary>
        internal static string DefaultReportNameRdlx {
            get {
                return ResourceManager.GetString("DefaultReportNameRdlx", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Untitled.rpx.
        /// </summary>
        internal static string DefaultReportNameRpx {
            get {
                return ResourceManager.GetString("DefaultReportNameRpx", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string DirtySign {
            get {
                return ResourceManager.GetString("DirtySign", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Disable Shortcuts.
        /// </summary>
        internal static string DisableShortcutsText {
            get {
                return ResourceManager.GetString("DisableShortcutsText", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports_Excel.xlsx.
        /// </summary>
        internal static string Excel2007FileName {
            get {
                return ResourceManager.GetString("Excel2007FileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Excel 2007 files (*.xlsx)|*.xlsx|Excel files (*.xls)|*.xls|All files (*.*)|*.*.
        /// </summary>
        internal static string Excel2007Filter {
            get {
                return ResourceManager.GetString("Excel2007Filter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports_Excel.xls.
        /// </summary>
        internal static string ExcelFileName {
            get {
                return ResourceManager.GetString("ExcelFileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Excel files (*.xls)|*.xls|All files (*.*)|*.*.
        /// </summary>
        internal static string ExcelFilter {
            get {
                return ResourceManager.GetString("ExcelFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Export Complete.
        /// </summary>
        internal static string ExportCompleteString {
            get {
                return ResourceManager.GetString("ExportCompleteString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportText {
            get {
                return ResourceManager.GetString("ExportText", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports_HTML.html.
        /// </summary>
        internal static string HTMLFileName {
            get {
                return ResourceManager.GetString("HTMLFileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Html files (*.htm)|*.html|All files (*.*)|*.*.
        /// </summary>
        internal static string HTMLFilter {
            get {
                return ResourceManager.GetString("HTMLFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports_Image.
        /// </summary>
        internal static string ImageFileName {
            get {
                return ResourceManager.GetString("ImageFileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Image files(*.BMP;*.EMF;*.GIF;*.JPEG;*.TIFF;*.PNG)|*.BMP;*.EMF;*.GIF;*.JPEG;*.TIFF;*.PNG.
        /// </summary>
        internal static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Could not load specified file. Specified File format is not supported.
        /// </summary>
        internal static string InvalidFileText {
            get {
                return ResourceManager.GetString("InvalidFileText", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Open from server....
        /// </summary>
        internal static string LoadFromServer {
            get {
                return ResourceManager.GetString("LoadFromServer", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NewText {
            get {
                return ResourceManager.GetString("NewText", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to All Report Files (*.rpx;*.rdlx;*rdlx-master)|*.rpx;*.rdlx;*rdlx-master|Section Report Files (*.rpx)|*.rpx|Page Report Files (*.rdlx)|*.rdlx|RDL Report Files (*.rdlx;*.rdlx-master)|*.rdlx;*.rdlx-master|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenFileFilter {
            get {
                return ResourceManager.GetString("OpenFileFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenText {
            get {
                return ResourceManager.GetString("OpenText", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Comma-Separated Values (CSV).
        /// </summary>
        internal static string PageCsvString {
            get {
                return ResourceManager.GetString("PageCsvString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel Worksheet - Layout(XLS, XLSX).
        /// </summary>
        internal static string PageExcelRE {
            get {
                return ResourceManager.GetString("PageExcelRE", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel Worksheet(XLS, XLSX).
        /// </summary>
        internal static string PageExcelString {
            get {
                return ResourceManager.GetString("PageExcelString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Hyper Text Markup Language(HTML).
        /// </summary>
        internal static string PageHTMLString {
            get {
                return ResourceManager.GetString("PageHTMLString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Image Format( BMP , EMP , GIF , JPEG , TIFF, PNG ).
        /// </summary>
        internal static string PageImageString {
            get {
                return ResourceManager.GetString("PageImageString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Portable Document Format(PDF).
        /// </summary>
        internal static string PagePDFString {
            get {
                return ResourceManager.GetString("PagePDFString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Report Document Format(RDF).
        /// </summary>
        internal static string PageRDFString {
            get {
                return ResourceManager.GetString("PageRDFString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Page Report Files (*.rdlx)|*.rdlx.
        /// </summary>
        internal static string PageReportFilter {
            get {
                return ResourceManager.GetString("PageReportFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel Worksheet - Data(XLS).
        /// </summary>
        internal static string PageTransformationDeviceString {
            get {
                return ResourceManager.GetString("PageTransformationDeviceString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word Document(DOC, DOCX).
        /// </summary>
        internal static string PageWordString {
            get {
                return ResourceManager.GetString("PageWordString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Extensible Markup Language(XML).
        /// </summary>
        internal static string PageXMLString {
            get {
                return ResourceManager.GetString("PageXMLString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports_PDF.pdf.
        /// </summary>
        internal static string PDFFileName {
            get {
                return ResourceManager.GetString("PDFFileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Pdf files (*.pdf)|*.pdf|All files (*.*)|*.*.
        /// </summary>
        internal static string PDFFilter {
            get {
                return ResourceManager.GetString("PDFFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports_RDF.rdf.
        /// </summary>
        internal static string RDFFileName {
            get {
                return ResourceManager.GetString("RDFFileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Rdf files (*.rdf)|*.rdf|All files (*.*)|*.*.
        /// </summary>
        internal static string RdfFilter {
            get {
                return ResourceManager.GetString("RdfFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to RDL Report Files (*.rdlx)|*.rdlx.
        /// </summary>
        internal static string RDLReportFilter {
            get {
                return ResourceManager.GetString("RDLReportFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to RDL Report Master files (*.rdlx-master)|*.rdlx-master.
        /// </summary>
        internal static string RDLReportFilterMaster {
            get {
                return ResourceManager.GetString("RDLReportFilterMaster", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to rdlx files|*.rdlx.
        /// </summary>
        internal static string RdlxFilter {
            get {
                return ResourceManager.GetString("RdlxFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Report has been changed!!Do you wish to save it?.
        /// </summary>
        internal static string ReportDirtyMessage {
            get {
                return ResourceManager.GetString("ReportDirtyMessage", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports_RTF.rtf.
        /// </summary>
        internal static string RtfFileName {
            get {
                return ResourceManager.GetString("RtfFileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Rtf files (*.rtf)|*.rtf|All files (*.*)|*.*.
        /// </summary>
        internal static string RtfFilter {
            get {
                return ResourceManager.GetString("RtfFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string SaveAsText {
            get {
                return ResourceManager.GetString("SaveAsText", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Save to server....
        /// </summary>
        internal static string SaveToServer {
            get {
                return ResourceManager.GetString("SaveToServer", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel WorkBook( XLS , XLSX ).
        /// </summary>
        internal static string SectionExcelString {
            get {
                return ResourceManager.GetString("SectionExcelString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Hypertext Markup Language(HTML).
        /// </summary>
        internal static string SectionHTMLString {
            get {
                return ResourceManager.GetString("SectionHTMLString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Portable Document Format(PDF).
        /// </summary>
        internal static string SectionPDFString {
            get {
                return ResourceManager.GetString("SectionPDFString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Plain Text(TXT).
        /// </summary>
        internal static string SectionPlainTextString {
            get {
                return ResourceManager.GetString("SectionPlainTextString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Section Report Files (*.rpx)|*.rpx.
        /// </summary>
        internal static string SectionReportFilter {
            get {
                return ResourceManager.GetString("SectionReportFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Rich Text Format(RTF).
        /// </summary>
        internal static string SectionRTFString {
            get {
                return ResourceManager.GetString("SectionRTFString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Tagged Image Format(TIFF).
        /// </summary>
        internal static string SectionTIFFString {
            get {
                return ResourceManager.GetString("SectionTIFFString", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports_Text.txt.
        /// </summary>
        internal static string TextFileName {
            get {
                return ResourceManager.GetString("TextFileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to txt files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        internal static string TextFilter {
            get {
                return ResourceManager.GetString("TextFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports_Tiff.tiff.
        /// </summary>
        internal static string TiffFileName {
            get {
                return ResourceManager.GetString("TiffFileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Tiff files (*.tiff)|*.tiff|All files (*.*)|*.*.
        /// </summary>
        internal static string TiffFilter {
            get {
                return ResourceManager.GetString("TiffFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to End User Designer.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string ToolBoxData {
            get {
                return ResourceManager.GetString("ToolBoxData", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports_Word.docx.
        /// </summary>
        internal static string Word2007FileName {
            get {
                return ResourceManager.GetString("Word2007FileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to MS Word files (*.docx)|*.docx|All files (*.*)|*.*.
        /// </summary>
        internal static string Word2007Filter {
            get {
                return ResourceManager.GetString("Word2007Filter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports_Word.doc.
        /// </summary>
        internal static string WordFileName {
            get {
                return ResourceManager.GetString("WordFileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to MS Word files (*.doc)|*.doc|All files (*.*)|*.*.
        /// </summary>
        internal static string WordFilter {
            get {
                return ResourceManager.GetString("WordFilter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ActiveReports_XML.xml.
        /// </summary>
        internal static string XMLFileName {
            get {
                return ResourceManager.GetString("XMLFileName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Xml files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string XmlFilter {
            get {
                return ResourceManager.GetString("XmlFilter", resourceCulture);
            }
        }
    }
}
