'------------------------------------------------------------------------------
' <auto-generated>
'	 This code was generated by a tool.
'	 Runtime Version:4.0.30319.18063
'	 Changes to this file may cause incorrect behavior and will be lost if
'	 the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Option Strict On
Option Explicit On
Imports System
Namespace My.Resources
	'This class was auto-generated by the StronglyTypedResourceBuilder
	'class via a tool like ResGen or Visual Studio.
	'To add or remove a member, edit your .ResX file then rerun ResGen
	'with the /str option, or rebuild your VS project.
	'''<summary>
	'''  A strongly-typed resource class, for looking up localized strings, etc.
	'''</summary>
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), _
	 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
	 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
	Friend Class Resource
		Private Shared resourceMan As Global.System.Resources.ResourceManager
		Private Shared resourceCulture As Global.System.Globalization.CultureInfo
		<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
			MyBase.New()
		End Sub
		'''<summary>
		'''  Returns the cached ResourceManager instance used by this class.
		'''</summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GrapeCity.ActiveReports.Samples.EndUserDesigner.Resource", GetType(Resource).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property
		'''<summary>
		'''  Overrides the current thread's CurrentUICulture property for all
		'''  resource lookups using this strongly typed resource class.
		'''</summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(value As Global.System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property
		'''<summary>
		'''  Looks up a localized resource of type System.Drawing.Bitmap.
		'''</summary>
		Friend Shared ReadOnly Property CmdNewReport() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CmdNewReport", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized resource of type System.Drawing.Bitmap.
		'''</summary>
		Friend Shared ReadOnly Property CmdOpen() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CmdOpen", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized resource of type System.Drawing.Bitmap.
		'''</summary>
		Friend Shared ReadOnly Property CmdOpenFromServer() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CmdOpenFromServer", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized resource of type System.Drawing.Bitmap.
		'''</summary>
		Friend Shared ReadOnly Property CmdSave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CmdSave", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized resource of type System.Drawing.Bitmap.
		'''</summary>
		Friend Shared ReadOnly Property CmdSaveAs() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CmdSaveAs", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized resource of type System.Drawing.Bitmap.
		'''</summary>
		Friend Shared ReadOnly Property CmdSaveToServer() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CmdSaveToServer", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to ActiveReports_CSV.csv.
		'''</summary>
		Friend Shared ReadOnly Property CsvFileName() As String
			Get
				Return ResourceManager.GetString("CsvFileName", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to CSV Files (*.csv)|*.csv|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property CsvFilter() As String
			Get
				Return ResourceManager.GetString("CsvFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Untitled.rdlx.
		'''</summary>
		Friend Shared ReadOnly Property DefaultReportNameRdlx() As String
			Get
				Return ResourceManager.GetString("DefaultReportNameRdlx", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Untitled.rpx.
		'''</summary>
		Friend Shared ReadOnly Property DefaultReportNameRpx() As String
			Get
				Return ResourceManager.GetString("DefaultReportNameRpx", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to *.
		'''</summary>
		Friend Shared ReadOnly Property DirtySign() As String
			Get
				Return ResourceManager.GetString("DirtySign", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Disable Shortcuts.
		'''</summary>
		Friend Shared ReadOnly Property DisableShortcutsText() As String
			Get
				Return ResourceManager.GetString("DisableShortcutsText", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to ActiveReports_Excel.xlsx.
		'''</summary>
		Friend Shared ReadOnly Property Excel2007FileName() As String
			Get
				Return ResourceManager.GetString("Excel2007FileName", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Excel 2007 files (*.xlsx)|*.xlsx|Excel files (*.xls)|*.xls|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property Excel2007Filter() As String
			Get
				Return ResourceManager.GetString("Excel2007Filter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to ActiveReports_Excel.xls.
		'''</summary>
		Friend Shared ReadOnly Property ExcelFileName() As String
			Get
				Return ResourceManager.GetString("ExcelFileName", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Excel files (*.xls)|*.xls|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property ExcelFilter() As String
			Get
				Return ResourceManager.GetString("ExcelFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Exit.
		'''</summary>
		Friend Shared ReadOnly Property ExitText() As String
			Get
				Return ResourceManager.GetString("ExitText", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized resource of type System.Drawing.Bitmap.
		'''</summary>
		Friend Shared ReadOnly Property export() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("export", resourceCulture)
				Return CType(obj, System.Drawing.Bitmap)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Export Complete.
		'''</summary>
		Friend Shared ReadOnly Property ExportCompleteString() As String
			Get
				Return ResourceManager.GetString("ExportCompleteString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Export.
		'''</summary>
		Friend Shared ReadOnly Property ExportText() As String
			Get
				Return ResourceManager.GetString("ExportText", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to ActiveReports_HTML.html.
		'''</summary>
		Friend Shared ReadOnly Property HTMLFileName() As String
			Get
				Return ResourceManager.GetString("HTMLFileName", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Html files (*.htm)|*.html|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property HTMLFilter() As String
			Get
				Return ResourceManager.GetString("HTMLFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to ActiveReports_Image.
		'''</summary>
		Friend Shared ReadOnly Property ImageFileName() As String
			Get
				Return ResourceManager.GetString("ImageFileName", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Image files(*.BMP;*.EMF;*.GIF;*.JPEG;*.TIFF;*.PNG)|*.BMP;*.EMF;*.GIF;*.JPEG;*.TIFF;*.PNG.
		'''</summary>
		Friend Shared ReadOnly Property ImageFilter() As String
			Get
				Return ResourceManager.GetString("ImageFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Could not load specified file. Specified File format is not supported.
		'''</summary>
		Friend Shared ReadOnly Property InvalidFileText() As String
			Get
				Return ResourceManager.GetString("InvalidFileText", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Open from server....
		'''</summary>
		Friend Shared ReadOnly Property LoadFromServer() As String
			Get
				Return ResourceManager.GetString("LoadFromServer", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to New.
		'''</summary>
		Friend Shared ReadOnly Property NewText() As String
			Get
				Return ResourceManager.GetString("NewText", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to All Report Files (*.rpx;*.rdlx;*rdlx-master)|*.rpx;*.rdlx;*rdlx-master|Section Report Files (*.rpx)|*.rpx|Page Report Files (*.rdlx)|*.rdlx|RDL Report Files (*.rdlx;*.rdlx-master)|*.rdlx;*.rdlx-master|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property OpenFileFilter() As String
			Get
				Return ResourceManager.GetString("OpenFileFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Open.
		'''</summary>
		Friend Shared ReadOnly Property OpenText() As String
			Get
				Return ResourceManager.GetString("OpenText", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Comma-Separated Values (CSV).
		'''</summary>
		Friend Shared ReadOnly Property PageCsvString() As String
			Get
				Return ResourceManager.GetString("PageCsvString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Microsoft Excel Worksheet - Layout(XLS, XLSX).
		'''</summary>
		Friend Shared ReadOnly Property PageExcelRE() As String
			Get
				Return ResourceManager.GetString("PageExcelRE", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Microsoft Excel Worksheet(XLS, XLSX).
		'''</summary>
		Friend Shared ReadOnly Property PageExcelString() As String
			Get
				Return ResourceManager.GetString("PageExcelString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Hyper Text Markup Language(HTML).
		'''</summary>
		Friend Shared ReadOnly Property PageHTMLString() As String
			Get
				Return ResourceManager.GetString("PageHTMLString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Image Format( BMP , EMP , GIF , JPEG , TIFF, PNG ).
		'''</summary>
		Friend Shared ReadOnly Property PageImageString() As String
			Get
				Return ResourceManager.GetString("PageImageString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Portable Document Format(PDF).
		'''</summary>
		Friend Shared ReadOnly Property PagePDFString() As String
			Get
				Return ResourceManager.GetString("PagePDFString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Report Document Format(RDF).
		'''</summary>
		Friend Shared ReadOnly Property PageRDFString() As String
			Get
				Return ResourceManager.GetString("PageRDFString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Page Report Files (*.rdlx)|*.rdlx.
		'''</summary>
		Friend Shared ReadOnly Property PageReportFilter() As String
			Get
				Return ResourceManager.GetString("PageReportFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Microsoft Excel Worksheet - Data(XLS).
		'''</summary>
		Friend Shared ReadOnly Property PageTransformationDeviceString() As String
			Get
				Return ResourceManager.GetString("PageTransformationDeviceString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Microsoft Word Document(DOC, DOCX).
		'''</summary>
		Friend Shared ReadOnly Property PageWordString() As String
			Get
				Return ResourceManager.GetString("PageWordString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Extensible Markup Language(XML).
		'''</summary>
		Friend Shared ReadOnly Property PageXMLString() As String
			Get
				Return ResourceManager.GetString("PageXMLString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to ActiveReports_PDF.pdf.
		'''</summary>
		Friend Shared ReadOnly Property PDFFileName() As String
			Get
				Return ResourceManager.GetString("PDFFileName", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Pdf files (*.pdf)|*.pdf|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property PDFFilter() As String
			Get
				Return ResourceManager.GetString("PDFFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to ActiveReports_RDF.rdf.
		'''</summary>
		Friend Shared ReadOnly Property RDFFileName() As String
			Get
				Return ResourceManager.GetString("RDFFileName", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Rdf files (*.rdf)|*.rdf|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property RdfFilter() As String
			Get
				Return ResourceManager.GetString("RdfFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to RDL Report Files (*.rdlx)|*.rdlx.
		'''</summary>
		Friend Shared ReadOnly Property RDLReportFilter() As String
			Get
				Return ResourceManager.GetString("RDLReportFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to RDL Report Master files (*.rdlx-master)|*.rdlx-master.
		'''</summary>
		Friend Shared ReadOnly Property RDLReportFilterMaster() As String
			Get
				Return ResourceManager.GetString("RDLReportFilterMaster", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to rdlx files|*.rdlx.
		'''</summary>
		Friend Shared ReadOnly Property RdlxFilter() As String
			Get
				Return ResourceManager.GetString("RdlxFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Report has been changed!!Do you wish to save it?.
		'''</summary>
		Friend Shared ReadOnly Property ReportDirtyMessage() As String
			Get
				Return ResourceManager.GetString("ReportDirtyMessage", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to ActiveReports_RTF.rtf.
		'''</summary>
		Friend Shared ReadOnly Property RtfFileName() As String
			Get
				Return ResourceManager.GetString("RtfFileName", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Rtf files (*.rtf)|*.rtf|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property RtfFilter() As String
			Get
				Return ResourceManager.GetString("RtfFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Save As.
		'''</summary>
		Friend Shared ReadOnly Property SaveAsText() As String
			Get
				Return ResourceManager.GetString("SaveAsText", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Save.
		'''</summary>
		Friend Shared ReadOnly Property SaveText() As String
			Get
				Return ResourceManager.GetString("SaveText", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Save to server....
		'''</summary>
		Friend Shared ReadOnly Property SaveToServer() As String
			Get
				Return ResourceManager.GetString("SaveToServer", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Microsoft Excel WorkBook( XLS , XLSX ).
		'''</summary>
		Friend Shared ReadOnly Property SectionExcelString() As String
			Get
				Return ResourceManager.GetString("SectionExcelString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Hypertext Markup Language(HTML).
		'''</summary>
		Friend Shared ReadOnly Property SectionHTMLString() As String
			Get
				Return ResourceManager.GetString("SectionHTMLString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Portable Document Format(PDF).
		'''</summary>
		Friend Shared ReadOnly Property SectionPDFString() As String
			Get
				Return ResourceManager.GetString("SectionPDFString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Plain Text(TXT).
		'''</summary>
		Friend Shared ReadOnly Property SectionPlainTextString() As String
			Get
				Return ResourceManager.GetString("SectionPlainTextString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Section Report Files (*.rpx)|*.rpx.
		'''</summary>
		Friend Shared ReadOnly Property SectionReportFilter() As String
			Get
				Return ResourceManager.GetString("SectionReportFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Rich Text Format(RTF).
		'''</summary>
		Friend Shared ReadOnly Property SectionRTFString() As String
			Get
				Return ResourceManager.GetString("SectionRTFString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Tagged Image Format(TIFF).
		'''</summary>
		Friend Shared ReadOnly Property SectionTIFFString() As String
			Get
				Return ResourceManager.GetString("SectionTIFFString", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to ActiveReports_Text.txt.
		'''</summary>
		Friend Shared ReadOnly Property TextFileName() As String
			Get
				Return ResourceManager.GetString("TextFileName", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to txt files (*.txt)|*.txt|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property TextFilter() As String
			Get
				Return ResourceManager.GetString("TextFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to ActiveReports_Tiff.tiff.
		'''</summary>
		Friend Shared ReadOnly Property TiffFileName() As String
			Get
				Return ResourceManager.GetString("TiffFileName", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Tiff files (*.tiff)|*.tiff|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property TiffFilter() As String
			Get
				Return ResourceManager.GetString("TiffFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to End User Designer.
		'''</summary>
		Friend Shared ReadOnly Property Title() As String
			Get
				Return ResourceManager.GetString("Title", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Data.
		'''</summary>
		Friend Shared ReadOnly Property ToolBoxData() As String
			Get
				Return ResourceManager.GetString("ToolBoxData", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to ActiveReports_Word.docx.
		'''</summary>
		Friend Shared ReadOnly Property Word2007FileName() As String
			Get
				Return ResourceManager.GetString("Word2007FileName", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to MS Word files (*.docx)|*.docx|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property Word2007Filter() As String
			Get
				Return ResourceManager.GetString("Word2007Filter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to ActiveReports_Word.doc.
		'''</summary>
		Friend Shared ReadOnly Property WordFileName() As String
			Get
				Return ResourceManager.GetString("WordFileName", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to MS Word files (*.doc)|*.doc|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property WordFilter() As String
			Get
				Return ResourceManager.GetString("WordFilter", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to ActiveReports_XML.xml.
		'''</summary>
		Friend Shared ReadOnly Property XMLFileName() As String
			Get
				Return ResourceManager.GetString("XMLFileName", resourceCulture)
			End Get
		End Property
		'''<summary>
		'''  Looks up a localized string similar to Xml files (*.xml)|*.xml|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property XmlFilter() As String
			Get
				Return ResourceManager.GetString("XmlFilter", resourceCulture)
			End Get
		End Property
	End Class
End Namespace
