//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.34003
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GrapeCity.ActiveReports.Samples.Layer.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrapeCity.ActiveReports.Samples.Layer.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap CmdNewReport {
			get {
				object obj = ResourceManager.GetObject("CmdNewReport", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap CmdOpen {
			get {
				object obj = ResourceManager.GetObject("CmdOpen", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap CmdSave {
			get {
				object obj = ResourceManager.GetObject("CmdSave", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap CmdSaveAs {
			get {
				object obj = ResourceManager.GetObject("CmdSaveAs", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Exit.
		/// </summary>
		internal static string ExitText {
			get {
				return ResourceManager.GetString("ExitText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Export Complete.
		/// </summary>
		internal static string ExportCompleteString {
			get {
				return ResourceManager.GetString("ExportCompleteString", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to PDF Export.
		/// </summary>
		internal static string ExportText {
			get {
				return ResourceManager.GetString("ExportText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Could not load specified file. Specified File format is not supported.
		/// </summary>
		internal static string InvalidFileText {
			get {
				return ResourceManager.GetString("InvalidFileText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to New.
		/// </summary>
		internal static string NewText {
			get {
				return ResourceManager.GetString("NewText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to All Report Files (*.rpx;*.rdlx;*rdlx-master)|*.rpx;*.rdlx;*rdlx-master|Section Report Files (*.rpx)|*.rpx|Page Report Files (*.rdlx)|*.rdlx|RDL Report Files (*.rdlx;*.rdlx-master)|*.rdlx;*.rdlx-master|All files (*.*)|*.*.
		/// </summary>
		internal static string OpenFileFilter {
			get {
				return ResourceManager.GetString("OpenFileFilter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Open.
		/// </summary>
		internal static string OpenText {
			get {
				return ResourceManager.GetString("OpenText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Page Report Files (*.rdlx)|*.rdlx.
		/// </summary>
		internal static string PageReportFilter {
			get {
				return ResourceManager.GetString("PageReportFilter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ActiveReports_PDF.pdf.
		/// </summary>
		internal static string PDFFileName {
			get {
				return ResourceManager.GetString("PDFFileName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Pdf files (*.pdf)|*.pdf|All files (*.*)|*.*.
		/// </summary>
		internal static string PDFFilter {
			get {
				return ResourceManager.GetString("PDFFilter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to RDL Report Files (*.rdlx)|*.rdlx.
		/// </summary>
		internal static string RDLReportFilter {
			get {
				return ResourceManager.GetString("RDLReportFilter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to RDL Report Master files (*.rdlx-master)|*.rdlx-master.
		/// </summary>
		internal static string RDLReportFilterMaster {
			get {
				return ResourceManager.GetString("RDLReportFilterMaster", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to rdlx files|*.rdlx.
		/// </summary>
		internal static string RdlxFilter {
			get {
				return ResourceManager.GetString("RdlxFilter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Report has been changed!!Do you wish to save it?.
		/// </summary>
		internal static string ReportDirtyMessage {
			get {
				return ResourceManager.GetString("ReportDirtyMessage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Save As.
		/// </summary>
		internal static string SaveAsText {
			get {
				return ResourceManager.GetString("SaveAsText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Save.
		/// </summary>
		internal static string SaveText {
			get {
				return ResourceManager.GetString("SaveText", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Section Report Files (*.rpx)|*.rpx.
		/// </summary>
		internal static string SectionReportFilter {
			get {
				return ResourceManager.GetString("SectionReportFilter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Data.
		/// </summary>
		internal static string ToolBoxData {
			get {
				return ResourceManager.GetString("ToolBoxData", resourceCulture);
			}
		}
	}
}
