//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.34014
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GrapeCity.ActiveReports.Samples.RdfViewer.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		/// <summary>
		///Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrapeCity.ActiveReports.Samples.RdfViewer.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		/// <summary>
		///	Overrides the current thread's CurrentUICulture property for all
		///	resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		/// <summary>
		///   Looks up a localized string similar to ActiveReports_Excel.xlsx.
		/// </summary>
		internal static string Excel2007FileName {
			get {
				return ResourceManager.GetString("Excel2007FileName", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to Excel 2007 files (*.xlsx)|*.xlsx|Excel files (*.xls)|*.xls|All files (*.*)|*.*.
		/// </summary>
		internal static string Excel2007Filter {
			get {
				return ResourceManager.GetString("Excel2007Filter", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to ActiveReports_Excel.xlsx.
		/// </summary>
		internal static string ExcelFileName {
			get {
				return ResourceManager.GetString("ExcelFileName", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to Excel files (*.xls)|*.xls|All files (*.*)|*.*.
		/// </summary>
		internal static string ExcelFilter {
			get {
				return ResourceManager.GetString("ExcelFilter", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to Export Complete.
		/// </summary>
		internal static string ExportCompleteString {
			get {
				return ResourceManager.GetString("ExportCompleteString", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to ActiveReports_HTML.html.
		/// </summary>
		internal static string HTMLFileName {
			get {
				return ResourceManager.GetString("HTMLFileName", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to Html files (*.htm)|*.html|All files (*.*)|*.*.
		/// </summary>
		internal static string HTMLFilter {
			get {
				return ResourceManager.GetString("HTMLFilter", resourceCulture);
			}
		}
		
		/// <summary>
		///   
		/// Looks up a localized string similar to ActiveReports_PDF.pdf.
		/// </summary>
		internal static string PDFFileName {
			get {
				return ResourceManager.GetString("PDFFileName", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to Pdf files (*.pdf)|*.pdf|All files (*.*)|*.*.
		/// </summary>
		internal static string PDFFilter {
			get {
				return ResourceManager.GetString("PDFFilter", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to ActiveReports_RTF.rtf.
		/// </summary>
		internal static string RtfFileName {
			get {
				return ResourceManager.GetString("RtfFileName", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to Rtf files (*.rtf)|*.rtf|All files (*.*)|*.*.
		/// </summary>
		internal static string RtfFilter {
			get {
				return ResourceManager.GetString("RtfFilter", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to Microsoft Excel WorkBook( XLS , XLSX ).
		/// </summary>
		internal static string SectionExcelString {
			get {
				return ResourceManager.GetString("SectionExcelString", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to Hypertext Markup Language(HTML).
		/// </summary>
		internal static string SectionHTMLString {
			get {
				return ResourceManager.GetString("SectionHTMLString", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to Portable Document Format(PDF).
		/// </summary>
		internal static string SectionPDFString {
			get {
				return ResourceManager.GetString("SectionPDFString", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to Plain Text(TXT).
		/// </summary>
		internal static string SectionPlainTextString {
			get {
				return ResourceManager.GetString("SectionPlainTextString", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to Rich Text Format(RTF).
		/// </summary>
		internal static string SectionRTFString {
			get {
				return ResourceManager.GetString("SectionRTFString", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to Tagged Image Format(TIFF).
		/// </summary>
		internal static string SectionTIFFString {
			get {
				return ResourceManager.GetString("SectionTIFFString", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to ActiveReports_Text.txt.
		/// </summary>
		internal static string TextFileName {
			get {
				return ResourceManager.GetString("TextFileName", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to txt files (*.txt)|*.txt|All files (*.*)|*.*.
		/// </summary>
		internal static string TextFilter {
			get {
				return ResourceManager.GetString("TextFilter", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to ActiveReports_Tiff.tiff.
		/// </summary>
		internal static string TiffFileName {
			get {
				return ResourceManager.GetString("TiffFileName", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to Tiff files (*.tiff)|*.tiff|All files (*.*)|*.*.
		/// </summary>
		internal static string TiffFilter {
			get {
				return ResourceManager.GetString("TiffFilter", resourceCulture);
			}
		}
	}
}
