'------------------------------------------------------------------------------
' <auto-generated>
'	 This code was generated by a tool.
'	 Changes to this file may cause incorrect behavior and will be lost if
'	 the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------
Option Strict On
Option Explicit On
Partial Public Class FlashViewerIntro
	'''<summary>
	'''Head1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead
	'''<summary>
	'''form1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
	'''<summary>
	'''ViewerOptionsPanel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewerOptionsPanel As Global.System.Web.UI.WebControls.Panel
	'''<summary>
	'''ShowSplitter control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ShowSplitter As Global.System.Web.UI.WebControls.CheckBox
	'''<summary>
	'''ShowToc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ShowToc As Global.System.Web.UI.WebControls.CheckBox
	'''<summary>
	'''ShowThumbnails control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ShowThumbnails As Global.System.Web.UI.WebControls.CheckBox
	'''<summary>
	'''ShowToolbar control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ShowToolbar As Global.System.Web.UI.WebControls.CheckBox
	'''<summary>
	'''InsertButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents InsertButton As Global.System.Web.UI.WebControls.CheckBox
	'''<summary>
	'''LanguageLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LanguageLabel As Global.System.Web.UI.WebControls.Label
	'''<summary>
	'''LanguageDropDownList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LanguageDropDownList As Global.System.Web.UI.WebControls.DropDownList
	'''<summary>
	'''ThemesLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ThemesLabel As Global.System.Web.UI.WebControls.Label
	'''<summary>
	'''ThemesDropDownList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ThemesDropDownList As Global.System.Web.UI.WebControls.DropDownList
	'''<summary>
	'''ReportsLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ReportsLabel As Global.System.Web.UI.WebControls.Label
	'''<summary>
	'''ReportsDropDownList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ReportsDropDownList As Global.System.Web.UI.WebControls.DropDownList
	'''<summary>
	'''ViewReportButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewReportButton As Global.System.Web.UI.WebControls.Button
End Class
