'------------------------------------------------------------------------------
' <auto-generated>
'	 This code was generated by a tool.
'	 Runtime Version:4.0.30319.34003
'	 Changes to this file may cause incorrect behavior and will be lost if
'	 the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Option Strict On
Option Explicit On
Imports System
Namespace My.Resources
	
	'This class was auto-generated by the StronglyTypedResourceBuilder
	'class via a tool like ResGen or Visual Studio.
	'To add or remove a member, edit your .ResX file then rerun ResGen
	'with the /str option, or rebuild your VS project.
	'''<summary>
	'''  A strongly-typed resource class, for looking up localized strings, etc.
	'''</summary>
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
	 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
	 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
	Friend Class Resource
		
		Private Shared resourceMan As Global.System.Resources.ResourceManager
		
		Private Shared resourceCulture As Global.System.Globalization.CultureInfo
		
		<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
		Friend Sub New()
			MyBase.New
		End Sub
		
		'''<summary>
		'''  Returns the cached ResourceManager instance used by this class.
		'''</summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GrapeCity.ActiveReports.Samples.Layer.Resource", GetType(Resource).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property
		
		'''<summary>
		'''  Overrides the current thread's CurrentUICulture property for all
		'''  resource lookups using this strongly typed resource class.
		'''</summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set
				resourceCulture = value
			End Set
		End Property
		
		'''<summary>
		'''  Looks up a localized resource of type System.Drawing.Bitmap.
		'''</summary>
		Friend Shared ReadOnly Property CmdNewReport() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CmdNewReport", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized resource of type System.Drawing.Bitmap.
		'''</summary>
		Friend Shared ReadOnly Property CmdOpen() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CmdOpen", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized resource of type System.Drawing.Bitmap.
		'''</summary>
		Friend Shared ReadOnly Property CmdSave() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CmdSave", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized resource of type System.Drawing.Bitmap.
		'''</summary>
		Friend Shared ReadOnly Property CmdSaveAs() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("CmdSaveAs", resourceCulture)
				Return CType(obj,System.Drawing.Bitmap)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to Exit.
		'''</summary>
		Friend Shared ReadOnly Property ExitText() As String
			Get
				Return ResourceManager.GetString("ExitText", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to Export Complete.
		'''</summary>
		Friend Shared ReadOnly Property ExportCompleteString() As String
			Get
				Return ResourceManager.GetString("ExportCompleteString", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to PDF Export.
		'''</summary>
		Friend Shared ReadOnly Property ExportText() As String
			Get
				Return ResourceManager.GetString("ExportText", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to Could not load specified file. Specified File format is not supported.
		'''</summary>
		Friend Shared ReadOnly Property InvalidFileText() As String
			Get
				Return ResourceManager.GetString("InvalidFileText", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to New.
		'''</summary>
		Friend Shared ReadOnly Property NewText() As String
			Get
				Return ResourceManager.GetString("NewText", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to All Report Files (*.rpx;*.rdlx;*rdlx-master)|*.rpx;*.rdlx;*rdlx-master|Section Report Files (*.rpx)|*.rpx|Page Report Files (*.rdlx)|*.rdlx|RDL Report Files (*.rdlx;*.rdlx-master)|*.rdlx;*.rdlx-master|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property OpenFileFilter() As String
			Get
				Return ResourceManager.GetString("OpenFileFilter", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to Open.
		'''</summary>
		Friend Shared ReadOnly Property OpenText() As String
			Get
				Return ResourceManager.GetString("OpenText", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to Page Report Files (*.rdlx)|*.rdlx.
		'''</summary>
		Friend Shared ReadOnly Property PageReportFilter() As String
			Get
				Return ResourceManager.GetString("PageReportFilter", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to ActiveReports_PDF.pdf.
		'''</summary>
		Friend Shared ReadOnly Property PDFFileName() As String
			Get
				Return ResourceManager.GetString("PDFFileName", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to Pdf files (*.pdf)|*.pdf|All files (*.*)|*.*.
		'''</summary>
		Friend Shared ReadOnly Property PDFFilter() As String
			Get
				Return ResourceManager.GetString("PDFFilter", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to RDL Report Files (*.rdlx)|*.rdlx.
		'''</summary>
		Friend Shared ReadOnly Property RDLReportFilter() As String
			Get
				Return ResourceManager.GetString("RDLReportFilter", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to RDL Report Master files (*.rdlx-master)|*.rdlx-master.
		'''</summary>
		Friend Shared ReadOnly Property RDLReportFilterMaster() As String
			Get
				Return ResourceManager.GetString("RDLReportFilterMaster", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to rdlx files|*.rdlx.
		'''</summary>
		Friend Shared ReadOnly Property RdlxFilter() As String
			Get
				Return ResourceManager.GetString("RdlxFilter", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to Report has been changed!!Do you wish to save it?.
		'''</summary>
		Friend Shared ReadOnly Property ReportDirtyMessage() As String
			Get
				Return ResourceManager.GetString("ReportDirtyMessage", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to Save As.
		'''</summary>
		Friend Shared ReadOnly Property SaveAsText() As String
			Get
				Return ResourceManager.GetString("SaveAsText", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to Save.
		'''</summary>
		Friend Shared ReadOnly Property SaveText() As String
			Get
				Return ResourceManager.GetString("SaveText", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to Section Report Files (*.rpx)|*.rpx.
		'''</summary>
		Friend Shared ReadOnly Property SectionReportFilter() As String
			Get
				Return ResourceManager.GetString("SectionReportFilter", resourceCulture)
			End Get
		End Property
		
		'''<summary>
		'''  Looks up a localized string similar to Data.
		'''</summary>
		Friend Shared ReadOnly Property ToolBoxData() As String
			Get
				Return ResourceManager.GetString("ToolBoxData", resourceCulture)
			End Get
		End Property
	End Class
End Namespace
